name: 'Changie release'
description: 'Create a changie release'
branding:
  icon: 'award'
  color: 'green'

inputs:
  github-token:
    description: 'The GitHub token'
    required: true

  release-workflow:
    description: "Name of the release workflow to trigger"
    default: "release.yaml"
    required: false

runs:
  using: "composite"
  steps:

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          changelog:
            - CHANGELOG.md
          notes:
            - added: .changes/*.md
          templates:
            - added: .changes/*.tpl.md

    - name: Check for changelog items
      id: drafts
      run: |
        if find .changes/unreleased/ -name '*.yaml' | grep .;  then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Output changes
      if: steps.drafts.outputs.exists == 'true'
      uses: miniscruff/changie-action@b6d52c80deb236a5b548f8774cd5a18b87da9e9a # v1.0.1
      id: changelog
      with:
        version: latest
        args: batch --dry-run auto

    - name: Batch changes
      if: steps.drafts.outputs.exists == 'true'
      uses: miniscruff/changie-action@b6d52c80deb236a5b548f8774cd5a18b87da9e9a # v1.0.1
      with:
        version: latest
        args: batch auto

    - name: Merge changes
      if: steps.drafts.outputs.exists == 'true'
      uses: miniscruff/changie-action@b6d52c80deb236a5b548f8774cd5a18b87da9e9a # v1.0.1
      with:
        version: latest
        args: merge

    - name: Get the latest version
      id: latest
      if: steps.drafts.outputs.exists == 'true' || (steps.changes.outputs.changelog == 'true' && steps.changes.outputs.notes == 'true')
      uses: miniscruff/changie-action@b6d52c80deb236a5b548f8774cd5a18b87da9e9a # v1.0.1
      with:
        version: latest
        args: latest

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      if: steps.drafts.outputs.exists == 'true'
      with:
        title: Release ${{ steps.latest.outputs.output }}
        branch: release/${{ steps.latest.outputs.output }}
        commit-message: Release ${{ steps.latest.outputs.output }}
        token: ${{ inputs.github-token }}
        body: |
          This PR was created by the [Changie release GitHub action](https://github.com/labd/changie-release-action). When you're ready to do a release, you can merge this and the tag ${{ steps.latest.outputs.output}} will be created and the release workflow will be started.  If you're not ready to do a release yet, that's fine, whenever you add more changes to main, this PR will be updated.

          # Releases
          ${{ steps.changelog.outputs.output }}

    - name: Create tag
      if: steps.changes.outputs.changelog == 'true' && steps.changes.outputs.notes == 'true' && steps.changes.outputs.templates == 'false'
      uses: actions/github-script@v6
      env:
        version: ${{ steps.latest.outputs.output }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${process.env.version}`,
            sha: context.sha
          })

    - name: Create release notes
      if: steps.changes.outputs.changelog == 'true' && steps.changes.outputs.notes == 'true' && steps.changes.outputs.templates == 'false'
      shell: bash
      id: release-notes
      run: |
        BODY=$(cat .changes/${{ steps.latest.outputs.output }}.md | sed -n '1!p')

        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "body<<$EOF" >> $GITHUB_OUTPUT
        echo "$BODY" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub release
      if: steps.changes.outputs.changelog == 'true' && steps.changes.outputs.notes == 'true' && steps.changes.outputs.templates == 'false'
      uses: actions/github-script@v6
      env:
        version: ${{ steps.latest.outputs.output }}
      with:
        github-token: ${{ inputs.github-token }}
        retries: 3
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: process.env.version,
            body: `${{ steps.release-notes.outputs.body }}`,
            tag_name: process.env.version,
            draft: false,
          })

    # We need to manually trigger a release workflow since GitHub actions cannot
    # automatically trigger other GitHub actions.
    - name: Trigger release
      if: steps.changes.outputs.changelog == 'true' && steps.changes.outputs.notes == 'true' && steps.changes.outputs.templates == 'false' && inputs.release-workflow != ''
      shell: bash
      run: gh workflow run ${{ inputs.release-workflow }} --ref ${{ steps.latest.outputs.output }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
